version: 0.2

phases:
  install:
    commands:
      - yum update -y
  pre_build:
    commands:
      - echo pre_build completed on `date`
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo build completed on `date`
      - databricks --help
  post_build:
    commands:
      - echo post_build completed on `date`
